### ISSUE TITLE
Setup Github Actions 

### ISSUE THREAD

**Issue by hariclerry** [hariclerry/mediawiki#20]
Setup Github Actions

##TODO
- [ ] Run npm ci
- [ ] Run linter in CI (github actions, npm run lint)
- [ ] Run  playwright test

**Comment by hariclerry** [comment]
CC: @vidhi-mody @und3fined-v01d @zeljkofilipin
